import "./index.css";
import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import ModalProvider from "@/components/providers/ModalProvider";
const font = Inter_Tight({
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Scrapmatic",
  description: "Generated by hejzbh Hazim Tulumovic. All rights reserved",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider loginUrl="/api/auth/login" profileUrl="/api/auth/me">
        <body className={`bg-bodyGradient ${font.className} antialiased`}>
          {children}
          <ModalProvider />
        </body>
      </UserProvider>
    </html>
  );
}
